modLoader="javafml"

loaderVersion="[28,)"
license="MIT LICENSE"

[[mods]]
modId="danmachi"
version="${file.jarVersion}"
displayName="Danmachi Mod"
authors="ImNotJahan"
description='''
Adds stuff from the wonderful world of danmachi.
'''
