modLoader="javafml"

loaderVersion="[28,)"
license="MIT LICENSE"

[[mods]]
modId="danmachi"
version="1.2.1"
displayName="Danmachi Mod"
updateJSONURL="https://raw.githubusercontent.com/ImNotJahan/danmachi-mod/master/update.json"
authors="ImNotJahan"
credits="flammeprinsessen1, Xanax"
description='''
Adds stuff from the wonderful world of danmachi.
'''

[[dependencies.danmachi]]
        modId="geckolib3"
        mandatory=true
        versionRange="3.0.0-beta.8,"
        ordering="BEFORE"
        side="BOTH"