name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Minecraft Architectury Tests
      uses: ValkyrienSkies/Minecraft-Architectury-Testing@v1.7
      
